const mongoose = require("mongoose");
const Timetable = require("./timetable"); 

// 1. dotenv को लोड करें ताकि .env फाइल से पासवर्ड मिल सके
require('dotenv').config();

// 2. mongoURI की जगह process.env.MONGO_URI का इस्तेमाल करें
mongoose.connect(process.env.MONGO_URI)
  .then(() => console.log("Connected to MongoDB for bulk seeding... 🚀"))
  .catch(err => console.log("Connection Error:", err));

const timetableData = [
  // ================= BA DATA =================
  { course: "BA", day: "Monday", lecture: "1", subject: "History" },
  { course: "BA", day: "Monday", lecture: "2", subject: "Mathematics" },
  { course: "BA", day: "Monday", lecture: "3", subject: "Geography of india" },
  { course: "BA", day: "Monday", lecture: "4", subject: "Gandhi's political" },
  { course: "BA", day: "Monday", lecture: "5", subject: "Gujarati lekhan" },
  { course: "BA", day: "Tuesday", lecture: "1", subject: "History" },
  { course: "BA", day: "Tuesday", lecture: "2", subject: "Mathematics" },
  { course: "BA", day: "Tuesday", lecture: "3", subject: "Geography of india" },
  { course: "BA", day: "Tuesday", lecture: "4", subject: "Gandhi's political" },
  { course: "BA", day: "Tuesday", lecture: "5", subject: "Gujarati lekhan" },
  { course: "BA", day: "Wednesday", lecture: "1", subject: "Mathematics" },
  { course: "BA", day: "Wednesday", lecture: "2", subject: "History" },
  { course: "BA", day: "Wednesday", lecture: "3", subject: "Geography of india" },
  { course: "BA", day: "Wednesday", lecture: "4", subject: "Gandhi's political" },
  { course: "BA", day: "Wednesday", lecture: "5", subject: "Gujarati lekhan" },
  { course: "BA", day: "Thursday", lecture: "1", subject: "Mathematics" },
  { course: "BA", day: "Thursday", lecture: "2", subject: "History" },
  { course: "BA", day: "Thursday", lecture: "3", subject: "Geography of india" },
  { course: "BA", day: "Thursday", lecture: "4", subject: "Gandhi's political" },
  { course: "BA", day: "Thursday", lecture: "5", subject: "Gujarati lekhan" },
  { course: "BA", day: "Friday", lecture: "1", subject: "Function grammar & composition" },
  { course: "BA", day: "Friday", lecture: "2", subject: "Science & technology" },
  { course: "BA", day: "Friday", lecture: "3", subject: "Science & technology" },
  { course: "BA", day: "Friday", lecture: "4", subject: "Geography of india" },
  { course: "BA", day: "Friday", lecture: "5", subject: "Gujarati lekhan kaushal" },
  { course: "BA", day: "Saturday", lecture: "1", subject: "Function grammar & composition" },
  { course: "BA", day: "Saturday", lecture: "2", subject: "Science & technology" },
  { course: "BA", day: "Saturday", lecture: "3", subject: "Mathematics" },
  { course: "BA", day: "Saturday", lecture: "4", subject: "History" },
  { course: "BA", day: "Saturday", lecture: "5", subject: "Gandhi's political though" },
  { course: "BA", day: "Sunday", lecture: "1", subject: "Holiday" },
  { course: "BA", day: "Sunday", lecture: "2", subject: "Holiday" },
  { course: "BA", day: "Sunday", lecture: "3", subject: "Holiday" },
  { course: "BA", day: "Sunday", lecture: "4", subject: "Holiday" },
  { course: "BA", day: "Sunday", lecture: "5", subject: "Holiday" },

  // ================= BBA DATA =================
  { course: "BBA", day: "Monday", lecture: "1", subject: "Fundamentals of EXIM" },
  { course: "BBA", day: "Monday", lecture: "2", subject: "Grooming and personality Development" },
  { course: "BBA", day: "Monday", lecture: "3", subject: "Digital marketing" },
  { course: "BBA", day: "Monday", lecture: "4", subject: "Entrepreneurship & MSME management" },
  { course: "BBA", day: "Monday", lecture: "5", subject: "Financial Accounting" },
  { course: "BBA", day: "Tuesday", lecture: "1", subject: "Fundamentals of EXIM" },
  { course: "BBA", day: "Tuesday", lecture: "2", subject: "Business analytics & intelligence" },
  { course: "BBA", day: "Tuesday", lecture: "3", subject: "Digital marketing" },
  { course: "BBA", day: "Tuesday", lecture: "4", subject: "Entrepreneurship & MSME management" },
  { course: "BBA", day: "Tuesday", lecture: "5", subject: "Financial Accounting" },
  { course: "BBA", day: "Wednesday", lecture: "1", subject: "Fundamentals of EXIM" },
  { course: "BBA", day: "Wednesday", lecture: "2", subject: "Grooming and personality Development" },
  { course: "BBA", day: "Wednesday", lecture: "3", subject: "Entrepreneurship & MSME management" },
  { course: "BBA", day: "Wednesday", lecture: "4", subject: "Business analytics & intelligence" },
  { course: "BBA", day: "Wednesday", lecture: "5", subject: "Financial Accounting" },
  { course: "BBA", day: "Thursday", lecture: "1", subject: "Fundamentals of EXIM" },
  { course: "BBA", day: "Thursday", lecture: "2", subject: "Business analytics & intelligence" },
  { course: "BBA", day: "Thursday", lecture: "3", subject: "Entrepreneurship & MSME management" },
  { course: "BBA", day: "Thursday", lecture: "4", subject: "Business analytics & intelligence" },
  { course: "BBA", day: "Thursday", lecture: "5", subject: "Digital Transformation" },
  { course: "BBA", day: "Friday", lecture: "1", subject: "Fundamentals of EXIM" },
  { course: "BBA", day: "Friday", lecture: "2", subject: "Grooming and personality Development" },
  { course: "BBA", day: "Friday", lecture: "3", subject: "Entrepreneurship & MSME management" },
  { course: "BBA", day: "Friday", lecture: "4", subject: "Grooming and personality Development" },
  { course: "BBA", day: "Friday", lecture: "5", subject: "Digital Transformation" },
  { course: "BBA", day: "Saturday", lecture: "1", subject: "Fundamentals of EXIM" },
  { course: "BBA", day: "Saturday", lecture: "2", subject: "Business analytics & intelligence" },
  { course: "BBA", day: "Saturday", lecture: "3", subject: "Business analytics & intelligence" },
  { course: "BBA", day: "Saturday", lecture: "4", subject: "Oasis Hour" },
  { course: "BBA", day: "Saturday", lecture: "5", subject: "Oasis Hour" },
  { course: "BBA", day: "Sunday", lecture: "1", subject: "Holiday" },
  { course: "BBA", day: "Sunday", lecture: "2", subject: "Holiday" },
  { course: "BBA", day: "Sunday", lecture: "3", subject: "Holiday" },
  { course: "BBA", day: "Sunday", lecture: "4", subject: "Holiday" },
  { course: "BBA", day: "Sunday", lecture: "5", subject: "Holiday" },

  // ================= AI AND ML DATA =================
  { course: "AIANDML", day: "Monday", lecture: "1", subject: "Grooming and personality" },
  { course: "AIANDML", day: "Monday", lecture: "2", subject: "Python programming" },
  { course: "AIANDML", day: "Monday", lecture: "3", subject: "Data handling" },
  { course: "AIANDML", day: "Monday", lecture: "4", subject: "AI automation" },
  { course: "AIANDML", day: "Monday", lecture: "5", subject: "Dynamic web" },
  { course: "AIANDML", day: "Tuesday", lecture: "1", subject: "Digital marketing" },
  { course: "AIANDML", day: "Tuesday", lecture: "2", subject: "Python programming" },
  { course: "AIANDML", day: "Tuesday", lecture: "3", subject: "Data handling" },
  { course: "AIANDML", day: "Tuesday", lecture: "4", subject: "AI automation" },
  { course: "AIANDML", day: "Tuesday", lecture: "5", subject: "Dynamic web" },
  { course: "AIANDML", day: "Wednesday", lecture: "1", subject: "Digital marketing" },
  { course: "AIANDML", day: "Wednesday", lecture: "2", subject: "Python programming" },
  { course: "AIANDML", day: "Wednesday", lecture: "3", subject: "Data handling" },
  { course: "AIANDML", day: "Wednesday", lecture: "4", subject: "AI automation" },
  { course: "AIANDML", day: "Wednesday", lecture: "5", subject: "Dynamic web" },
  { course: "AIANDML", day: "Thursday", lecture: "1", subject: "Operating System" },
  { course: "AIANDML", day: "Thursday", lecture: "2", subject: "Python programming" },
  { course: "AIANDML", day: "Thursday", lecture: "3", subject: "Data handling" },
  { course: "AIANDML", day: "Thursday", lecture: "4", subject: "AI automation" },
  { course: "AIANDML", day: "Thursday", lecture: "5", subject: "Dynamic web" },
  { course: "AIANDML", day: "Friday", lecture: "1", subject: "Operating System" },
  { course: "AIANDML", day: "Friday", lecture: "2", subject: "Python programming" },
  { course: "AIANDML", day: "Friday", lecture: "3", subject: "Data handling" },
  { course: "AIANDML", day: "Friday", lecture: "4", subject: "AI automation" },
  { course: "AIANDML", day: "Friday", lecture: "5", subject: "Dynamic web" },
  { course: "AIANDML", day: "Saturday", lecture: "1", subject: "Operating System" },
  { course: "AIANDML", day: "Saturday", lecture: "2", subject: "Operating System" },
  { course: "AIANDML", day: "Saturday", lecture: "3", subject: "Digital marketing" },
  { course: "AIANDML", day: "Saturday", lecture: "4", subject: "Oasis hour" },
  { course: "AIANDML", day: "Saturday", lecture: "5", subject: "Oasis hour" },
  { course: "AIANDML", day: "Sunday", lecture: "1", subject: "Holiday" },
  { course: "AIANDML", day: "Sunday", lecture: "2", subject: "Holiday" },
  { course: "AIANDML", day: "Sunday", lecture: "3", subject: "Holiday" },
  { course: "AIANDML", day: "Sunday", lecture: "4", subject: "Holiday" },
  { course: "AIANDML", day: "Sunday", lecture: "5", subject: "Holiday" },

  // ================= CYBER DATA =================
  { course: "CYBER", day: "Monday", lecture: "1", subject: "Grooming and personality" },
  { course: "CYBER", day: "Monday", lecture: "2", subject: "Python programming" },
  { course: "CYBER", day: "Monday", lecture: "3", subject: "Ethical Hacking" },
  { course: "CYBER", day: "Monday", lecture: "4", subject: "Ethical Hacking" },
  { course: "CYBER", day: "Monday", lecture: "5", subject: "Server Management" },
  { course: "CYBER", day: "Tuesday", lecture: "1", subject: "Digital marketing" },
  { course: "CYBER", day: "Tuesday", lecture: "2", subject: "Python programming" },
  { course: "CYBER", day: "Tuesday", lecture: "3", subject: "Ethical Hacking" },
  { course: "CYBER", day: "Tuesday", lecture: "4", subject: "Ethical Hacking" },
  { course: "CYBER", day: "Tuesday", lecture: "5", subject: "Server Management" },
  { course: "CYBER", day: "Wednesday", lecture: "1", subject: "Digital marketing" },
  { course: "CYBER", day: "Wednesday", lecture: "2", subject: "Python programming" },
  { course: "CYBER", day: "Wednesday", lecture: "3", subject: "Ethical Hacking" },
  { course: "CYBER", day: "Wednesday", lecture: "4", subject: "Ethical Hacking" },
  { course: "CYBER", day: "Wednesday", lecture: "5", subject: "Linux Administration" },
  { course: "CYBER", day: "Thursday", lecture: "1", subject: "Operating System" },
  { course: "CYBER", day: "Thursday", lecture: "2", subject: "Python programming" },
  { course: "CYBER", day: "Thursday", lecture: "3", subject: "Ethical Hacking" },
  { course: "CYBER", day: "Thursday", lecture: "4", subject: "Ethical Hacking" },
  { course: "CYBER", day: "Thursday", lecture: "5", subject: "Linux Administration" },
  { course: "CYBER", day: "Friday", lecture: "1", subject: "Operating System" },
  { course: "CYBER", day: "Friday", lecture: "2", subject: "Python programming" },
  { course: "CYBER", day: "Friday", lecture: "3", subject: "Ethical Hacking" },
  { course: "CYBER", day: "Friday", lecture: "4", subject: "Ethical Hacking" },
  { course: "CYBER", day: "Friday", lecture: "5", subject: "Linux Administration" },
  { course: "CYBER", day: "Saturday", lecture: "1", subject: "Operating System" },
  { course: "CYBER", day: "Saturday", lecture: "2", subject: "Operating system" },
  { course: "CYBER", day: "Saturday", lecture: "3", subject: "Server Management" },
  { course: "CYBER", day: "Saturday", lecture: "4", subject: "Oasis hours" },
  { course: "CYBER", day: "Saturday", lecture: "5", subject: "Oasis hours" },
  { course: "CYBER", day: "Sunday", lecture: "1", subject: "Holiday" },
  { course: "CYBER", day: "Sunday", lecture: "2", subject: "Holiday" },
  { course: "CYBER", day: "Sunday", lecture: "3", subject: "Holiday" },
  { course: "CYBER", day: "Sunday", lecture: "4", subject: "Holiday" },
  { course: "CYBER", day: "Sunday", lecture: "5", subject: "Holiday" },

  // ================= BVOC DATA =================
  { course: "BVOC", day: "Monday", lecture: "1", subject: "Digital Empowerment" },
  { course: "BVOC", day: "Monday", lecture: "2", subject: "No lecture" },
  { course: "BVOC", day: "Monday", lecture: "3", subject: "No lecture" },
  { course: "BVOC", day: "Monday", lecture: "4", subject: "No lecture" },
  { course: "BVOC", day: "Monday", lecture: "5", subject: "No lecture" },
  { course: "BVOC", day: "Tuesday", lecture: "1", subject: "Career Skill" },
  { course: "BVOC", day: "Tuesday", lecture: "2", subject: "No lecture" },
  { course: "BVOC", day: "Tuesday", lecture: "3", subject: "No lecture" },
  { course: "BVOC", day: "Tuesday", lecture: "4", subject: "No lecture" },
  { course: "BVOC", day: "Tuesday", lecture: "5", subject: "No lecture" },
  { course: "BVOC", day: "Wednesday", lecture: "1", subject: "Database Management System" },
  { course: "BVOC", day: "Wednesday", lecture: "2", subject: "No lecture" },
  { course: "BVOC", day: "Wednesday", lecture: "3", subject: "No lecture" },
  { course: "BVOC", day: "Wednesday", lecture: "4", subject: "No lecture" },
  { course: "BVOC", day: "Wednesday", lecture: "5", subject: "No lecture" },
  { course: "BVOC", day: "Thursday", lecture: "1", subject: "Digital Empowerment" },
  { course: "BVOC", day: "Thursday", lecture: "2", subject: "No lecture" },
  { course: "BVOC", day: "Thursday", lecture: "3", subject: "No lecture" },
  { course: "BVOC", day: "Thursday", lecture: "4", subject: "No lecture" },
  { course: "BVOC", day: "Thursday", lecture: "5", subject: "No lecture" },
  { course: "BVOC", day: "Friday", lecture: "1", subject: "Object Oriented programming - 1" },
  { course: "BVOC", day: "Friday", lecture: "2", subject: "No lecture" },
  { course: "BVOC", day: "Friday", lecture: "3", subject: "No lecture" },
  { course: "BVOC", day: "Friday", lecture: "4", subject: "No lecture" },
  { course: "BVOC", day: "Friday", lecture: "5", subject: "No lecture" },
  { course: "BVOC", day: "Saturday", lecture: "1", subject: "Object Oriented programming - 1" },
  { course: "BVOC", day: "Saturday", lecture: "2", subject: "No lecture" },
  { course: "BVOC", day: "Saturday", lecture: "3", subject: "No lecture" },
  { course: "BVOC", day: "Saturday", lecture: "4", subject: "No lecture" },
  { course: "BVOC", day: "Saturday", lecture: "5", subject: "No lecture" },
  { course: "BVOC", day: "Sunday", lecture: "1", subject: "Holiday" },
  { course: "BVOC", day: "Sunday", lecture: "2", subject: "Holiday" },
  { course: "BVOC", day: "Sunday", lecture: "3", subject: "Holiday" },
  { course: "BVOC", day: "Sunday", lecture: "4", subject: "Holiday" },
  { course: "BVOC", day: "Sunday", lecture: "5", subject: "Holiday" }
];

const seedDB = async () => {
  try {
    await Timetable.deleteMany({}); 
    await Timetable.insertMany(timetableData); 
    console.log("Full Timetable Seeded Successfully! ✅ Total entries:", timetableData.length);
    mongoose.connection.close();
  } catch (err) {
    console.log("Seeding Error:", err);
    process.exit(1);
  }
};

seedDB();